"""empty message

Revision ID: 0d132a10609c
Revises: d618d1624c74
Create Date: 2021-08-05 13:58:27.311175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d132a10609c'
down_revision = 'd618d1624c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('english', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('english', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('english', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('english', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('english', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('english', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('english', 'question',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('english', 'topic',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('english', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('english', 'qid')
    op.add_column('inter', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('inter', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inter', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inter', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inter', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inter', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inter', 'question',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('inter', 'topic',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('inter', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('inter', 'qid')
    op.add_column('math', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('math', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('math', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('math', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('math', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('math', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('math', 'question',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('math', 'topic',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('math', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('math', 'qid')
    op.add_column('social', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('social', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('social', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('social', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('social', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('social', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('social', 'question',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('social', 'topic',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('social', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('social', 'qid')
    op.add_column('storyoptions', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('storyoptions', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('storyoptions', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('storyoptions', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('storyoptions', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('storyoptions', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('storyoptions', 'storyid',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.drop_constraint('storyoptions_ibfk_1', 'storyoptions', type_='foreignkey')
    op.create_foreign_key(None, 'storyoptions', 'story', ['storyid'], ['id'])
    op.drop_column('storyoptions', 'qid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyoptions', sa.Column('qid', mysql.VARCHAR(length=3), nullable=True))
    op.drop_constraint(None, 'storyoptions', type_='foreignkey')
    op.create_foreign_key('storyoptions_ibfk_1', 'storyoptions', 'stories', ['storyid'], ['storyid'])
    op.alter_column('storyoptions', 'storyid',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('storyoptions', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('storyoptions', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('storyoptions', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('storyoptions', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('storyoptions', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('storyoptions', 'id')
    op.add_column('social', sa.Column('qid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('social', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('social', 'topic',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('social', 'question',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('social', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('social', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('social', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('social', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('social', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('social', 'id')
    op.add_column('math', sa.Column('qid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('math', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('math', 'topic',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('math', 'question',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('math', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('math', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('math', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('math', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('math', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('math', 'id')
    op.add_column('inter', sa.Column('qid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('inter', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('inter', 'topic',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('inter', 'question',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('inter', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('inter', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('inter', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('inter', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('inter', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('inter', 'id')
    op.add_column('english', sa.Column('qid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('english', 'usr_lvl',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('english', 'topic',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('english', 'question',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('english', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('english', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('english', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('english', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('english', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('english', 'id')
    op.create_table('bug_report',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report', mysql.TEXT(), nullable=True),
    sa.Column('date_reported', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inter_pdf',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inter_videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('social_videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('english_videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('headtopic', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('musician',
    sa.Column('ssn', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('ssn'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('math_pdf',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('questions',
    sa.Column('qid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('option_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('option_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('option_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('option_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('correct_answer', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('qid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stories',
    sa.Column('storyid', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('story', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('storyid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('science',
    sa.Column('qid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.TEXT(), nullable=True),
    sa.Column('usr_lvl', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.TEXT(), nullable=True),
    sa.Column('option_a', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_b', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_c', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_d', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('correct_answer', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('qid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('social_pdf',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('englishold',
    sa.Column('qid', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.TEXT(), nullable=True),
    sa.Column('usr_lvl', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.TEXT(), nullable=True),
    sa.Column('option_a', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_b', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_c', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_d', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('correct_answer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('explanation', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('new',
    sa.Column('qid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('option_a', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('option_b', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('option_c', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('option_d', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('correct_answer', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('explanation', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('qid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('instrument',
    sa.Column('instrument_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('musicial_key', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pdf',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('math_videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('english_pdf',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('story')
    # ### end Alembic commands ###
